# https://lint.travis-ci.org/
branches:
  only:
  - master
  - prod
  - test-travis
notifications:
  email: false
git:
  depth: 10
language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: i686-w64-mingw32-gcc
      services: [ docker ]
      env: HB_CI_THREADS=4

before_install:
  - mxe_pkgs=(
      mxe-{i686,x86-64}-w64-mingw32.shared-{cairo,file,ghostscript,icu4c,libmysqlclient,postgresql}
      mxe-{i686,x86-64}-w64-mingw32.static-{freeimage,gd});
    if [ "$TRAVIS_OS_NAME" = 'linux' ] && [ "$CC" = 'i686-w64-mingw32-gcc' ] && [ "$TRAVIS_SUDO" = 'true' ]; then
      docker pull ubuntu:yakkety;
      docker run  -v "${PWD}:${PWD}" -w "${PWD}" -t ubuntu:yakkety sh -c "
        apt-get -qq update &&
        apt-get -qq install binutils-mingw-w64 gcc-mingw-w64 g++-mingw-w64 p7zip-full dos2unix realpath
          wine-stable &&
        ./package/mxe_win_dl_mxe.sh mxe-x86-64-w64-mingw32.shared";
    fi;

script:
  - if [ "$CC" = 'i686-w64-mingw32-gcc' ]; then
      docker run ubuntu:xenial /package/mpkg_win_ci.sh
    fi;
