# https://lint.travis-ci.org/
branches:
  only:
  - master
  - prod
  - test-travis
notifications:
  email: false
git:
  depth: 10
language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: i686-w64-mingw32-gcc
      services: [ docker ]
      # https://hub.docker.com/_/ubuntu/
      env: [ HB_CI_THREADS=4, 'DOCKER_IMAGE=ubuntu:rolling' ]

script:
  - >
    if [ "$TRAVIS_OS_NAME" = 'linux' ] && [ "$CC" = 'i686-w64-mingw32-gcc' ] && [ "$TRAVIS_SUDO" = 'true' ]; then
      time docker pull "${DOCKER_IMAGE}"
      time docker run -it -v "${PWD}:${PWD}" -w "${PWD}" "${DOCKER_IMAGE}" sh -c ./.travis.sh
    fi
