# https://lint.travis-ci.org/
branches:
  only:
  - master
  - prod
  - test-travis
notifications:
  email: false
git:
  depth: 10
language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: i686-w64-mingw32-gcc
      services: [ docker ]
      # https://hub.docker.com/_/ubuntu/
      env: [ HB_CI_THREADS=4, 'DOCKER_IMAGE=ubuntu:rolling' ]

before_install:
  - >
    mxe_pkgs=( \
      mxe-{i686,x86-64}-w64-mingw32.shared-{cairo,file,ghostscript,icu4c,libmysqlclient,postgresql} \
      mxe-{i686,x86-64}-w64-mingw32.static-{freeimage,gd})
    if [ "$TRAVIS_OS_NAME" = 'linux' ] && [ "$CC" = 'i686-w64-mingw32-gcc' ] && [ "$TRAVIS_SUDO" = 'true' ]; then
      time docker pull "${DOCKER_IMAGE}"
      time docker run -it -v "${PWD}:${PWD}" -w "${PWD}" --cidfile linux.cid "${DOCKER_IMAGE}" sh -c "
        cat /etc/*-release
        ulimit -a
        ulimit -s 1082768
        ulimit -a
        df -h
        apt-get -qq update
        apt-get -qq install \
          curl dirmngr git gcc-6 binutils \
          binutils-mingw-w64 gcc-mingw-w64 g++-mingw-w64 p7zip-full dos2unix realpath wine-stable
        echo 'deb http://pkg.mxe.cc/repos/apt/debian wheezy main' > /etc/apt/sources.list.d/mxeapt.list
        curl -fsS --connect-timeout 15 --retry 3 'https://keyserver.ubuntu.com/pks/lookup?search=0xD43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB&op=get' \
        | gpg --import --status-fd 1
        gpg --export D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB \
        | apt-key add -
        apt-get -qq update
        sh -x ./package/mpkg_win_ci.sh --force"
    fi

script:
  - echo 'NOOP'
