# https://lint.travis-ci.org/
branches:
  only:
  - master
  - prod
  - test-travis
notifications:
  email: false
git:
  depth: 10
language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: i686-w64-mingw32-gcc
      services: [ docker ]
      # https://hub.docker.com/_/ubuntu/
      env: [ HB_CI_THREADS=4, 'DOCKER_IMAGE=ubuntu:rolling' ]

before_install:
  - mxe_pkgs=(
      mxe-{i686,x86-64}-w64-mingw32.shared-{cairo,file,ghostscript,icu4c,libmysqlclient,postgresql}
      mxe-{i686,x86-64}-w64-mingw32.static-{freeimage,gd});
    if [ "$TRAVIS_OS_NAME" = 'linux' ] && [ "$CC" = 'i686-w64-mingw32-gcc' ] && [ "$TRAVIS_SUDO" = 'true' ]; then
      docker pull "${DOCKER_IMAGE}";
      time docker run -v "${PWD}:${PWD}" -w "${PWD}" -t "${DOCKER_IMAGE}" sh -c "
        cat /etc/*-release;
        apt-get -qq update;
        apt-get -qq install binutils-mingw-w64 gcc-mingw-w64 g++-mingw-w64 p7zip-full curl dos2unix realpath wine-stable;
        echo 'deb http://pkg.mxe.cc/repos/apt/debian wheezy main' > /etc/apt/sources.list.d/mxeapt.list;
        curl -fsS --connect-timeout 15 --retry 3 'https://keyserver.ubuntu.com/pks/lookup?search=0xD43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB&op=get'
        | gpg --import --status-fd 1;
        gpg --export D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
        | apt-key add -;
        apt-get -qq update;
        apt-get -qq install ${mxe_pkgs[@]}";
    fi;

script:
  - if [ "$CC" = 'i686-w64-mingw32-gcc' ]; then
      echo '>>${DOCKER_IMAGE}<<';
      docker run -v "${PWD}:${PWD}" -w "${PWD}" -t "${DOCKER_IMAGE}" sh -c ./package/mpkg_win_ci.sh;
    fi;
