# https://lint.travis-ci.org/
branches:
  only:
  - master
  - prod
  - test-travis
notifications:
  email: false
git:
  depth: 10
language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: i686-w64-mingw32-gcc
      services: [ docker ]
      env: HB_CI_THREADS=4
      addons:
        apt:
          packages:
            - [ binutils-mingw-w64, gcc-mingw-w64, g++-mingw-w64, p7zip-full, gnupg-curl, dos2unix, realpath ]

before_install:
  - mxe_pkgs=(
      mxe-{i686,x86-64}-w64-mingw32.shared-{cairo,file,ghostscript,icu4c,libmysqlclient,postgresql}
      mxe-{i686,x86-64}-w64-mingw32.static-{freeimage,gd});
    if [ "$TRAVIS_OS_NAME" = 'linux' ] && [ "$CC" = 'i686-w64-mingw32-gcc' ] && [ "$TRAVIS_SUDO" = 'true' ]; then
      docker pull ubuntu:xenial;
      docker run ubuntu:xenial apt-get -qq update;
      docker run ubuntu:xenial apt-get -qq install wine;
      docker run ubuntu:xenial sh ls -lA;
      docker run ubuntu:xenial ./package/mxe_win_dl_mxe.sh "${mxe_pkgs[@]}";
    fi;

script:
  - if [ "$CC" = 'i686-w64-mingw32-gcc' ]; then
      docker run ubuntu:xenial ./package/mpkg_win_ci.sh
    fi;
